language: java
jdk:
  - oraclejdk8
sudo: false
env:
  - TASK=tests
  - TASK=checkstyle
  - TASK=kompos
script:
  - if [ "$TASK" = "tests" ];      then ant tests; fi
  - if [ "$TASK" = "checkstyle" ]; then ant checkstyle; fi
  - if [ "$TASK" = "kompos" ]; then nvm install 6 && ant && cd tools/kompos && npm install && npm test; fi
