language: java
jdk:
  - oraclejdk8
sudo: false
env:
  - TASK=tests
  - TASK=checkstyle
script:
  - if [ "$TASK" = "tests" ];      then ant tests; fi
  - if [ "$TASK" = "checkstyle" ]; then ant checkstyle-jar && ant checkstyle; fi
