language: java
jdk:
  - oraclejdk8
sudo: false
script:
  - ant
  - ./som -G core-lib/TestSuite/TestRunner.som
  - ./som -X core-lib/TestSuite/TestRunner.som
  - ant test
  - ant checkstyle-jar && ant checkstyle
